# Generated by Django 5.0.4 on 2024-11-12 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('diretor', models.CharField(max_length=20)),
                ('isPopular', models.BooleanField()),
                ('isDestaque', models.BooleanField()),
                ('isNovo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('obra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LibreflixApp.obra')),
                ('duracao', models.IntegerField()),
            ],
            bases=('LibreflixApp.obra',),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('obra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LibreflixApp.obra')),
                ('qntEpisodios', models.IntegerField()),
            ],
            bases=('LibreflixApp.obra',),
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.IntegerField()),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibreflixApp.serie')),
            ],
        ),
    ]
