# Generated by Django 5.0.4 on 2024-11-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreflixApp', '0002_rename_isnovo_obra_isrecente_episodio_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='imagem',
            field=models.URLField(),
        ),
    ]
