# Generated by Django 5.0.4 on 2024-11-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreflixApp', '0003_alter_obra_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='genero',
            field=models.CharField(default='Ação', max_length=20),
            preserve_default=False,
        ),
    ]
