# Generated by Django 5.0.4 on 2024-11-14 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreflixApp', '0004_obra_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='dataLancamento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
