# Generated by Django 5.0.4 on 2024-11-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreflixApp', '0005_obra_datalancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='descricao',
            field=models.TextField(default='vazio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episodio',
            name='titulo',
            field=models.CharField(default='vazio', max_length=20),
            preserve_default=False,
        ),
    ]
