# Generated by Django 5.0.4 on 2024-11-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreflixApp', '0007_alter_obra_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='trailer',
            field=models.URLField(default='https://www.youtube.com/watch?v=KHwdeFuKjTU'),
            preserve_default=False,
        ),
    ]
